### ISSUE TITLE
Applying patterns to kanban markdown file not working as expected

### ISSUE THREAD

**Issue by jesseleite** [jglev/obsidian-apply-patterns-plugin#54]
## Expected Behavior

I expect to be able to apply a pattern to any underlying markdown file, no matter whether in markdown editing mode, preview mode, live preview mode, or kanban board mode when using the kanban plugin.

## Current Behavior

I created a pattern and can apply it to a regular .md file, but not to a kanban .md file when viewing as a kanban board. I realize this is a plugin conflict with another plugin, but the 'apply pattern' command isn't even visible in the command palette when in kanban mode (but other plugin commands are visible in kanban mode.

## Steps to Reproduce

- Install [kanban](https://github.com/mgmeyers/obsidian-kanban)
- Create a kanban board
- Try to apply a pattern to a kanban board
    - This works when editing the kanban's markdown file directly
    - It doesn't work (the apply pattern command is not visible in the command palette) when in the kanban board preview mode

## Context (Environment)
* Obsidian version: 0.14.15
* Apply Patterns version: 2.1.1

## Possible Solution
Maybe if the command palette command was selectable while in kanban mode, apply patterns would still be able to operate on the underlying markdown file saved by kanban?

**Comment by jesseleite** [comment]
PS. Absolutely loving your plugin... thank you for all your work on this!

**Comment by jglev** [comment]
Thank you for taking the time to write! And for your kind words!

_(Your GitHub profile notes that you're a developer, so I've included some links in my comments below, in case they help to understand the context.)_

> the 'apply pattern' command isn't even visible in the command palette when in kanban mode (but other plugin commands are visible in kanban mode.

I haven't used the Kanban plugin until today, but I'm actually relieved to hear this -- This is expected behavior from Apply Patterns, which is meant only to show commands in instances where it can execute them (in this case, when it's in an ["Editor"](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L797) environment).

Apply Patterns makes heavy use of the Obsidian Editor API, in such a way that:

- It's not able (as currently intended / expected) to edit files while in non-Editor modes. Specifically, this means that it is able to work in Edit mode and in Live Preview mode, but not in Preview mode. (This is similar, I suspect, to the way in which Obsidian's native "`Search & replace in current file`" command is not accessible in Preview mode.)
- Looking through the Kanban plugin's codebase, I don't think that it is feasible to be able to hook into the Kanban plugin's edit behavior while in the plugin's non-Markdown / Kanban board mode. To my reading, the Kanban plugin is using React, and has implemented its own, React-based [edit function and state management](https://github.com/mgmeyers/obsidian-kanban/blob/0051d02fffe6500f76aced475ff029c297a84761/src/parsers/formats/list.ts#L272-L293), which then hook back into Obsidian's API periodically.

With that in mind, while I welcome anyone exploring this further, and would be happy to review Pull Requests related to this, I see this as being expected behavior for Apply Patterns, in such a way that is not likely to be changed.

With that said, again, thank you for taking the time to write this up!

**Comment by jesseleite** [comment]
@jglev Ah darn. Thought maybe it'd be trivial, given that every Kanban board is just a standard markdown note with a UX rendering mode on top. Right now I have to switch to edit mode, run the action, then switch back to Kanban mode. It works, it just feels like the action should be able to operate on the underlying markdown file somehow without all the mode switching.
